### ISSUE TITLE
what should I use

### ISSUE THREAD

**Issue by albertog** [dart-lang/polymer_interop#42]
There are two libraries which should I use.

polymer_interop
polymer.dart

**Comment by zoechi** [comment]
Use for what? If you want to use Polymer then use 
- https://pub.dartlang.org/packages/polymer 

version 1.0.0-rc.16 is the most recent. You need to click on `All xxx versions...` to find it because pre-releases (with a `-` in the version) are listed below normal releases.

You also probably want to use

- https://pub.dartlang.org/packages/polymer_elements 

version 1.0.0-rc.8 is the most recent here. Don't be discouraged by "Currently Unsupported" this applies only to an very old version. The front page is only updated when a normal release is published. The supported version is also still a pre-release.

Github issues are for bug reports and feature requests. For support questions please use other channels https://www.dartlang.org/support/
